"""Set up column profile_pic

Revision ID: 76bef4098120
Revises: bfede63987ef
Create Date: 2023-11-06 01:16:58.484221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76bef4098120'
down_revision = 'bfede63987ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
